site_name: AI Hardware Documentation
site_author: Asim Ansari
site_description: >-
  Comprehensive documentation for AI hardware, covering networking, GPUs, SDKs, deployment, monitoring, SOPs, and FAQs.

nav:
  - Network: index.md
  - GPU: GPU.md
  - SDK: sdk.md
  - Deployment: deployment.md
  - Monitoring: monitoring.md
  - SOP: SOP.md
  - FAQ: FAQ.md


theme: 
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.sticky
    - toc.integrate
    - toc.follow
    - toc.sticky
    - toc.collapsible
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.fade_in
    - theme.toggle
    - header.autohide
    - breadcrumb
    - navigation.footer
    - navigation.expand
    - content.code.select
    - content.code.annotate
    - content.code.fancy
    - navigation.path  # Shows navigation path for clarity
    - navigation.progress  # Adds a progress bar while scrolling

  language: en

  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: "#1a1a2e"  # Dark Navy Blue
      accent: "#ff5733"  # Bright Orange-Red
      secondary: "#0f3460"  # Deep Blue
      background: "#ffffff"  # White
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: "#121212"  # Dark Black
      accent: "#ffcc00"  # Bright Yellow
      secondary: "#222831"  # Dark Grey
      background: "#181818"  # Dark Gray

extra:
  smooth_scroll: true
  font:
    text: "Inter"  # Modern, clean typography
    code: "Fira Code"
  generator: false  # Hide "Generated by MkDocs Material"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ansari-asim
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/asim-ansari-19b383151
  extra_css:
    - stylesheets/custom.css
  extra_javascript:
    - javascripts/custom.js

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.tasklist  
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html

plugins:
  - search
  - git-revision-date-localized
  - social
  - minify:
      minify_html: true
  - table-reader  # Enables tables from CSV/Excel
  - glightbox  # Enables image lightbox feature

copyright: '&copy; 2025 <a href="https://github.com/ansari-asim" target="_blank" rel="noopener">Asim Ansari</a>'