site_name: AI Hardware Documentation
site_author: Asim Ansari
site_description: >-
  Comprehensive documentation for AI hardware, covering networking, GPUs, SDKs, deployment, monitoring, SOPs, and FAQs.

dev_addr: 127.0.0.1:8000

#repo_name: ansari-asim/ai-hardware-docs
#repo_url: https://github.com/ansari-asim/ai-hardware-docs

nav:
  - Network: index.md
  - GPU: GPU.md
  - SDK: sdk.md
  - Deployment: deployment.md
  - Monitoring: monitoring.md
  - SOP: SOP.md
  - FAQ: FAQ.md
  #- Issues: issues.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.sticky
    - toc.integrate
    - toc.follow
    - toc.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
    - header.autohide
    - navigation.footer
    - navigation.path
    - navigation.progress
    - content.code.annotate
    - announce.dismiss
  language: en
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Inter
    code: Fira Code

extra:
  homepage: https://ansari-asim.github.io/ai-hardware-docs
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to enhance your experience and analyze site usage. By continuing, you agree to our use of cookies.
    cookies:
      analytics: Analytics
    actions:
      - accept
      - manage
  analytics:
    provider: plausible
    domain: ansari-asim.github.io/ai-hardware-docs
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ansari-asim
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/asim-ansari-19b383151
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/asim_ansari
  generator: false

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/custom.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - admonition
  - meta

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+'
  - social
  - tags
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - table-reader
  - glightbox
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            heading_level: 2

copyright: '© 2025 <a href="https://github.com/ansari-asim" target="_blank" rel="noopener">Asim Ansari</a>'